version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: docker/Dockerfile.backend
    ports:
      - "5045:5045"
    volumes:
      - ./backend:/app
    environment:
      - PORT=5045
      - DB_NAME=booking
      - DB_USER=admin
      - DB_PASSWORD=password
      - DB_HOST=db
    depends_on:
      - db

  db:
    image: postgres:14
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: booking
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
