FROM node:18

# Créer le dossier de travail
WORKDIR /app

# Copier les fichiers package.json
COPY ./backend/package*.json ./

# Installer les dépendances
RUN npm install

# Copier tout le backend
COPY ./backend .

# Exposer le port 5045 (adapté à ton environnement)
EXPOSE 5045

# Lancer le serveur
CMD ["npm", "run", "dev"]
